### ISSUE TITLE
Input registers keys as released until key press.

### ISSUE THREAD

**Issue by HapticGames** [AcademyOfInteractiveEntertainment/aieBootstrap#1]
When using this in the update function:
`if (input->wasKeyReleased(aie::INPUT_KEY_W)) {
		std::cout << "W released";
	}`

It will continue to call W released until the W key is pressed for the first time, then it resumes to work like normal and only call release when the key is released.

**Comment by conanb** [comment]
I am fixing up the input system currently.

**Comment by conanb** [comment]
Issues fixed with latest updates.
