### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by intrepid249** [AcademyOfInteractiveEntertainment/aieBootstrap#2]
There are no methods to be able to get aie::Font width or height, for example I am making a button class, and I would like the text to be displayed according to the width as shown on the screen, relative to the font size, so that the text can be drawn in the centre of the button.
A lot of Font classes have a Font.stringWidth("String") that will determine the width of a string relative to the font.

edit:
Simple Fix - I added two methods within aie::Font.h to return the textureWidth and textureHeight variables as a const unsigned short so that they can be viewed but not edited externally

**Comment by terryn-aie** [comment]
No idea what our internal update policies are like, but I'd imagine that you could submit a PR to this repository with that small edit since I'm sure someone else might benefit from that down the line.

**Comment by intrepid249** [comment]
I'm not an author, so I can't I don't think

**Comment by terryn-aie** [comment]
You should be able to fork this repository, make a `patch-textureDims` branch on your forked repository, and then make a pull request (PR) on this repository. A PR essentially asks the maintainer of this project to review the changes that you made on that branch of your forked repository (intrepid249/aieBootstrap) and compare it against what is on the original repository (AIE/aieBootstrap). If they deem it properly well-written and formatted, then they should be able to incorporate it into the project.

If that happens, then you should rejoice! You will have contributed to making the aieBootstrap project better than it was before!

There's some [semi-OK documentation from GitHub](https://help.github.com/articles/fork-a-repo/) discussing the above process in further detail. If you're a student, I'd highly recommend that you seek out an instructor if you're having some trouble. (I could help you out too, though it'd be easier if you were my student.) Contributing to other projects is a great way to hone your skills and contribute to the development community at large; this could be first step towards that!

**Comment by conanb** [comment]
It appeared this method was already part of the Renderer2D class.
However it should not have been there as it made no use of Renderer2D.

I have now added these methods to the Font class, as well as one for finding the corner offsets of a rectangle that fits the string being draw. The method returns the bottom left corner (x0,y0) and top right corner (x1,y1) that can be combined with the position that you are rendering the string at to find a rectangle that perfectly fits the string.
