### ISSUE TITLE
Mouse Input

### ISSUE THREAD

**Issue by intrepid249** [AcademyOfInteractiveEntertainment/aieBootstrap#4]
A lot of games have the mouse 'locked' to a central position. using an impulse to get the deltaMouse coordinates then using this to affect the viewCamera. alternatively they wrap the cursor around the screen, so that the window never loses focus. It would be nice to have a method that allows me to manually set the screen coordinates for the mouse. Currently there are only 'getters'

**Comment by samcsss** [comment]
Mouse input is handled by GLFW
I suspect setting the position of the mouse is not what you really need (and very likely not possible anyway)
Take a look at the GLFW input guide: http://www.glfw.org/docs/latest/input_guide.html#input_mouse
You could try hiding the mouse cursor, as explained here: http://stackoverflow.com/questions/4431637/hiding-mouse-cursor-with-glfw
If you needed the mouse to wrap the screen, then I would hide the mouse cursor and draw my own.
There are other glfw options for controlling the behaviour of the mouse and window that may be worth exploring to achieve the functionality you want.
You should also note that this isn't a 'full featured' game engine. We're providing an absolute bare-bones framework for you to use as a starting point for your schoolwork. It is expected that any additional functionality students require would be written by the student.

**Comment by intrepid249** [comment]
Ok. Fair enough. Thanks for the pointers
