### ISSUE TITLE
Static singleton class Gizmos has no way of getting an instance

### ISSUE THREAD

**Issue by MandoCrusher** [AcademyOfInteractiveEntertainment/aieBootstrap#5]
I noticed that the singleton Input class in Bootstrap has a function called getInstance() whereas the Bootstrap singleton Gizmos class only has a public function called create which instantiates a static variable called 'sm_singleton'.

Logically this would let me use Gizmos::blablabla anywhere as long as I have the header file included but when I try and use Gizmos::clear() it throws up an error saying sm_singleton is a nullptr even though I have Gizmos::create() in the constructor of my class and it definitely is being called.

I can only logically assume that I need some way to get sm_singleton since it appears there's multiple instances of it, I'm tracking its journey through the code and sm_singleton is being set correctly by Gizmos::create() in my classes' constructor but once it gets to Gizmos::clear() it reads it as nullptr.

**Comment by conanb** [comment]
Within Bootstrap the Gizmos class is already initialised when the base Application code starts up, and is destroyed when the base Application closes. You should not need to call create/destroy in your own code.

The Gizmos class works more like a namespace, i.e. you call:

`Gizmos::addTransform()`

Rather than calling:

`Gizmos::getInstance()->addTransform()`
or:
```
Gizmos* gizmos = Gizmos::getInstance();
gizmos->addTransform()
```

Are you able to post a snippet of your code that is using Gizmos?

**Comment by MandoCrusher** [comment]
That's how I thought it worked. Here's the function in CameraNode.cpp that it wasn't able to deal with:

```
void CameraNode::Update(GLFWwindow* a_window, float a_dt, aie::Input* a_input, Vector2<int> a_originalMouseState, Vector4<float> a_target)
{
    // wipe the gizmos clean for this frame
    Gizmos::clear();

    // Update with mouse input
    UpdateInput(a_input, a_originalMouseState, a_dt);

    // Hide the mouse cursor
    glfwSetInputMode(a_window, GLFW_CURSOR, GLFW_CURSOR_HIDDEN);

    // Center cursor so we base camera rotations off of projected mouse movement instead of actual movement that could leave the window and cause extreme rotations
    glfwSetCursorPos(a_window, a_originalMouseState.x, a_originalMouseState.y);

    // Update camera view after getting new mouse input and orient to specified target
    UpdateView(a_target);
}
```
Essentially it tried to run Gizmos::clear() but deduced that the sm_singleton was nullptr and so the program crashed.

NOTE: CameraNode class is separate from 3DTestingGroundsApp which is inherting from aie::Application.

**Comment by MandoCrusher** [comment]
Just a bit of an update, I have my CameraNode class calling the Gizmos::draw() function but it's not actually drawing the Gizmos unless the draw function is in my _3DTestingGroundsApp.cpp which inherits from aie::Application.

**Comment by conanb** [comment]
So the CameraNode class is being used in an application that isn't using the Application base class?

Is your code initialising OpenGL correctly? And in the case of using your own base Application code you would need to call create() / destroy() on the Gizmos. Make sure your create call is happening after all OpenGL code has been initialised.

I'd need to see more of your code to see how it is all setup. I personally use Gizmos in lots of projects that aren't using Bootstrap; you just need to ensure OpenGL is fully initialised before calling Gizmos::create().

**Comment by conanb** [comment]
What was the status of this issue? What ended up being the root cause?

**Comment by richard-stern** [comment]
Since this is now two years old, I'm going to assume it's resolved.
