### ISSUE TITLE
Creating a font throws an exception

### ISSUE THREAD

**Issue by PancakesMan** [AcademyOfInteractiveEntertainment/aieBootstrap#6]
Upon downloading a fresh copy of bootstrap, loading it, setting Project2D as the startup project, and running it, Font.cpp throws an exception on line 60:
![image](https://cloud.githubusercontent.com/assets/13220410/26519816/27563eda-4306-11e7-9e47-bd52ad4e9fc6.png)

Thus far the solution has been simple. Don't use fonts in any projects. But now as we get into doing more complicated projects, being able to write text to the screen is very important for game menus, etc, and can no longer be avoided.

**Comment by conanb** [comment]
So this is a completely unmodified fresh fork / download?
You are trying to load the provided front located within the \bin\ folder?

What version of OpenGL does your PC support? Have you updated video drivers?

**Comment by samcsss** [comment]
Could not reproduce.

I downloaded a fresh copy of the repo, opened the bootstrap solution, set the 2D project as the startup project and the program executed as expected and without error.

If the Font constructor cannot find the font file to load, it will simply return null. 
The fact that this is giving you an exception on line 60 of Font.cpp makes me think it could be OpenGL related. 

Can you post some more information about your setup? 
I recall one student having issues due to their graphics card.

**Comment by PancakesMan** [comment]
![image](https://cloud.githubusercontent.com/assets/13220410/26540298/d841aea2-448f-11e7-8eec-e782fffc5cbb.png)
This is the info about my graphics card and opengl version found using a program called OpenGL Extensions Viewer. Here's a screenshot of dxdiag window if that helps too
![image](https://cloud.githubusercontent.com/assets/13220410/26540352/2fe5268e-4490-11e7-8ef3-eb53ba88fcc5.png)

**Comment by jaredmulconry** [comment]
glTexStorage2D wasn't in core OpenGL until 4.2. That's likely the issue there. The function pointer for it isn't getting loaded cause it's not supported.

**Comment by PancakesMan** [comment]
I tried updating my drivers and when it finished it changed the default video card to intel integrated graphics and wouldn't let me permanently change it back to AMD, which was running only on an app by app basis, it fixed the font issue but everything started drawing wrong: 
![image](https://cloud.githubusercontent.com/assets/13220410/26549263/43c1558e-44b7-11e7-817b-4449a4b1f555.png)

**Comment by jaredmulconry** [comment]
That looks like a bug specific to drawing of textures. I won't have time for a while to look into how the textures are being loaded to see if there's some other OpenGL version issue or corruption going on. @conanb Might you be able to offer some insights?

**Comment by terryn-aie** [comment]
Hello! Not sure if this is relevant anymore, but I took a look again before deleting the notification e-mail and noticed something odd...

The screenshot that you provided of the OpenGL Extensions Viewer suggests that your drivers are out of date considering that the version string indicates that you are running AMD Catalyst 8.882.2.3 whereas the last version of AMD Catalyst for your graphics card was version 15.7.1 released on 7/28/2015.

You'll want to visit the [AMD Download Center](http://support.amd.com/en-us/download) to download the latest version of your drivers for your laptop. After installation, you should inspect the latest OpenGL supported version via OpenGL Extensions Viewer again, which should indicate support for the 4.4 profile.

**Comment by terryn-aie** [comment]
Ah oops, I glossed over something else when I reread the post...

>I tried updating my drivers and when it finished it changed the default video card to intel integrated graphics

How did you update your drivers? Did you install the drivers from the AMD Download Center? You shouldn't have an issue switching your graphics between the iGPU (Intel) and the dGPU (AMD), but laptop drivers can be rather um, _annoying_ with those sorts of things...

Unfortunately, unless you gain support for OpenGL 4.4 or someone patches in some code to support older API levels of OpenGL, you won't be able to support fonts in your projects.

**Comment by PancakesMan** [comment]
I used a program from AMD that finds latest drivers and installs them. Can't remember what it was called as I deleted it. I worked around the issue by replacing the troublesome line
`glTexStorage2D(GL_TEXTURE_2D, 1, GL_R8, m_textureWidth, m_textureHeight);`
with the line
`glTexImage2D(GL_TEXTURE_2D, 0, GL_R8, m_textureWidth, m_textureHeight, 0, GL_RED, GL_UNSIGNED_BYTE, nullptr);`
This allows me to use fonts, as glTexImage2D is supported by the following versions of OpenGL:
![image](https://user-images.githubusercontent.com/13220410/27792115-5de18f74-6037-11e7-8725-0602c1ded230.png)
while glTexStorage2D is only supported by 4.2 and greater:
![image](https://user-images.githubusercontent.com/13220410/27792150-883803fc-6037-11e7-95e8-4f122a3a409c.png)

**Comment by conanb** [comment]
I have removed the glStorage2D and glTexSubImage2D and replaced with glTexImage2D to allow backwards compatibility.
