### ISSUE TITLE
aie::Input getPressedKeys().empty() is equating as true even when keys are being held.

### ISSUE THREAD

**Issue by MandoCrusher** [AcademyOfInteractiveEntertainment/aieBootstrap#8]
I've tried a bit of debugging concerning this such as displaying the size of the getPressedKeys vector and from what I can tell it is EXTREMELY inconsistent. what I'm assuming is happening is that the vector gets cleared every frame and then updated to the currently held keys before running the Application->update() logic.

however, within my player's update logic which is called in the Application->update(), the if statement that solely requires for getPressedKeys() to be empty is having its conditions met even if I have keys held down. I can affirm this by looking at the debug text in the console which fluctuates sparsely between having a size of 1 and a size of 0, meaning that regardless if it works in one frame, if it is incorrect in another frame its going to overwrite it and lead to wrong functionality through incorrect if statements.

**Comment by intrepid249** [comment]
Ok, so I've been doing a bit of looking into this, and the main reason for this, is that the onKeyRepeat function gets called on every repeat cycle. Which is _not_ every frame. I can verify this with some output testing to console. I output "Repeat" in the check statement for action == GLFW_REPEAT within Input.cpp
I output "Application update pressedKeys repeat" within my derived Application class inside a statement
if (!input->getPressedKeys().empty()) such that while I hold a key, it will output to console

finally I output "end of frame" at the bottom of while(!game_over) inside the base Application.cpp update in the bootstrap library to check for frame exit.

Console output can be seen here:
https://pastebin.com/sW0PkrY3

which demonstrates that getPressedKeys() is empty for numerous frames even while a key is held down

**Comment by MandoCrusher** [comment]
that would make sense. unfortunately, this makes having conditions for multi-button inputs very difficult since it means a condition for one button has to check against every other button that's involved in other input combinations. this is because it can't reliably tell that no other keys have been pressed.

since there doesn't seem to be any reliable way to get around this I'd suggest having a comment on getPressedKeys that says something along the lines of 'WARNING: does not update every single frame' so people that end up using getPressedKeys like this can quickly figure out what the issue is.

**Comment by conanb** [comment]
This can actually be overcome.

I will look into it. It's usually a simple matter of simply keeping this frame's and last frame's keys, then you can easily compare the two to determine press/release/up/down.

**Comment by conanb** [comment]
Issue fixed with latest update.
